### ISSUE TITLE
Should index be mandatory on split format?

### ISSUE THREAD

**Issue by asmodehn** [zblz/marshmallow-numerical#18]
Hi, and thanks for the work on this package ! 
I am also trying to get that working nicely together...

I recently encountered : 
```
{'index': ['Missing data for required field.']}
```
But I expected index to be optional (when not present assume range(n), same as pandas.DataFrame()

What do you think ?

**Comment by zblz** [comment]
I agree that it's not strictly necessary. We could set it as a configurable option, since in some situations you will want a required index (e.g., date time indices).

Thanks for the suggestion!

**Comment by zblz** [comment]
The change in PR #19 has been released in 0.1.4.
