### ISSUE TITLE
How to use a separate module?

### ISSUE THREAD

**Issue by xarpy** [zblz/marshmallow-numerical#20]
Hello, thank you very much for your project, I've been looking for a more practical way to do a schema treatment with pandas.

I would like some help, in my project, separated schema into a module and instantiate, for example, the class `DataSchema (SplitDataFrameSchema)`. But she dont recognize  Meta parameter, dtype, how can I dynamically assign it (based on the input data)?

**My structure in Tree:**
```
├── app
│   ├── api.py
│   ├── __init__.py
│   ├── db
│   │   ├── core.py
│   │   ├── __init__.py
│   ├── resources
│   │   ├── analysis_data.py
│   │   ├── __init__.py
│   ├── schemas.py
│   └── utils.py
├── config.py
├── connections.log
└── main.py
```
**My Schema code:**

```
from marshmallow_dataframe import SplitDataFrameSchema

class DataSchema(SplitDataFrameSchema):
    """Automatically generated schema for dataframe"""

    class Meta:
        dtypes = self.dtypes
```

**Comment by zblz** [comment]
Hi @xarpy - 

It seems like in the code above you try to set the  `dtypes` in `Meta` using `self.dtypes`. I don't think you can use `self` anywhere other than instance methods, and even if it worked it would be pointing at the `dtypes` attribute of the `DataSchema` instance. It would be good to see how you instantiate the schema, so a minimal working example would help.

In general, if you want to build a schema class dynamically based on input data, you can do something like:

```python
from marshmallow_dataframe import SplitDataFrameSchema

def build_schema_instance(input_dtypes):
    class DataSchema(SplitDataFrameSchema):
        """Automatically generated schema for dataframe"""

        class Meta:
            dtypes = input_dtypes

    return DataSchema()
```
